project_id = "pyoszlfqqvljwocrrafl"

[functions.cred-delete]
verify_jwt = true

[functions.cred-get]
verify_jwt = true

[functions.cred-list]
verify_jwt = true

[functions.cred-store]
verify_jwt = true

[functions.run-plan]
verify_jwt = true

[functions.execute-plan]
verify_jwt = true

[functions.challenge-create]
verify_jwt = true

[functions.notify]
verify_jwt = false

[functions.challenge-complete]
verify_jwt = false