// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyoszlfqqvljwocrrafl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5b3N6bGZxcXZsandvY3JyYWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzQzMzgsImV4cCI6MjA3MzAxMDMzOH0.BQokq7UNWZ3I1_wBS5FdILOvrv8oWn4xD4a5lzxokRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});